[package]
name = "imsz_c"
version = "0.2.0"
authors = [
    "Paulo Scardine <paulo@scardine.com.br>",
    "Mathias Panzenböck <grosser.meister.morti@gmx.net>"
]
edition = "2021"

[lib]
name = "imsz"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib"]

[dependencies]
imsz = { path = ".." }
