name: Documentation

on:
  push:
    branches:
    - main

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
    - name: Cache Debian Packages
      id: cache-debs
      uses: actions/cache@v2
      if: startsWith(runner.os, 'Linux')
      with:
        path: |
          /home/runner/debs
          /var/cache/apt/archives/*.deb
        key: ${{ runner.os }}-debs-2022-04-21_01:40:43

    - name: Install Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get install -q -y doxygen graphviz

    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - uses: Swatinem/rust-cache@v1

    - name: Build Documentation
      run: |
        cargo doc
        cd c
        make doc
        cd ..
        mv c/target/doxygen/html target/doc/c

    - name: Deploy Docs to GH-Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: target/doc
