name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cargo build --verbose
        cargo build --examples --verbose
        cd c
        cargo build

# TODO: find out why compiling the C example program doesn't work on GitHub
#        make

    - name: Run tests
      run: cargo test --verbose
